spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digikatdb
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
server:
  port: 8090
