spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:init_database.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/digikatdb
    username: postgres
    password: admin
  jpa:
    database: postgresql
server:
  port: 8090
